### ISSUE TITLE
Deterministic build process

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-sdk#136]
We should have a documented way to build runtimes based on the SDK deterministically, for both SGX and default targets (with priority on SGX targets). We should run daily tests on CI to make sure that at least the example runtimes in this repository can be built deterministically using the documented process.

**Comment by nhynes** [comment]
I tried this morning to use Nix via [crate2nix](https://crates.io/crates/crate2nix) and got pretty far until the bootstrap failed because of macos issues. So, if you need a VM to build with Nix, why not just build in a docker container? `cargo vendor` might help, but I think a lockfile will suffice.
